baseURL = "/"
languageCode = "ko-KR.UTF-8"
# title = "MathPhys2 Course - Mathematical Methods for Physicists"
title = "MathPhys2 Course - 2021"
# menuTitle = "MathPhys2 Course - 2021"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page.
  # editURL = ""
  author = "Jaejun Yu"
  description = "MathPhys2 Course"
  showVisitedLinks = false
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = true
  disableLandingPageButton = false
  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Home"
  disableLanguageSwitchingButton = true
  disableBreadcrumb = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  disableNextPrev = false
  # Order sections in menu by "weight" or "title".
  ordersectionsby = "weight"
  # default color scheme: "red", "blue", "green".
  themeVariant = "mine"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  # custom_css = ["css/foo.css", "css/bar.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "::"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Showcases"
url = "/showcase"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
